-- Placeholder load script for ETL phase (not implemented yet)
-- Expected flow:
-- 1) truncate stage/dw tables
-- 2) COPY cleaned CSV files generated by etl-scripts
-- 3) merge/upsert into fact tables

-- Example (to be activated in ETL phase):
-- COPY dw.fact_customer_orders FROM '/path/to/orders_clean.csv' CSV HEADER;
-- COPY dw.fact_customer_activity(customer_name, product, category, activity, activity_timestamp, device_type, session_id)
-- FROM '/path/to/activity_clean.csv' CSV HEADER;
